apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: game-system
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: flipper
    app.kubernetes.io/component: web
    app.kubernetes.io/managed-by: kustomize
data:
  NEXT_PUBLIC_API_URL: http://backend:8000
