apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: game-system
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: flipper
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
data:
  POSTGRES_DB: flipper
  POSTGRES_USER: flipper
  PGDATA: /var/lib/postgresql/data/pgdata
