apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: flipper-gateway
  namespace: game-system
  labels:
    app.kubernetes.io/part-of: flipper
    app.kubernetes.io/managed-by: kustomize
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      # allowedRoutes restricts which namespaces can bind HTTPRoutes to this Gateway
      allowedRoutes:
        namespaces:
          from: Same
