apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: game-system
data:
  # TODO: remplacer par le domaine de production réel
  NEXT_PUBLIC_API_URL: https://api.flipper.example.com
