apiVersion: v1
kind: Service
metadata:
  name: front-screen
  namespace: game-system
  labels:
    app.kubernetes.io/name: front-screen
    app.kubernetes.io/part-of: flipper
    app.kubernetes.io/component: screen
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: front-screen
  ports:
    - port: 80
      targetPort: 80
