apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../ressources
  - ../../gateway-api
  - ../../gateway-api/traefik

images:
  - name: backend
    newName: ghcr.io/flipgame-hetic/backend
    newTag: "1.0.0"
  - name: frontend
    newName: ghcr.io/flipgame-hetic/frontend
    newTag: "1.0.0"

patches:
  - path: patches/frontend-config.yaml
