apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: game-system
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: flipper
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
data:
  API_PORT: "8080"
  APP_ENV: production
  ALLOWED_ORIGINS: "http://localhost:3000"
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: flipper
  DATABASE_USER: flipper
