apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-sqlite-pvc
  namespace: game-system
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: flipper
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
